### ISSUE TITLE
Performance Delay After Using z Command to Navigate Directories

### ISSUE THREAD

**Issue by kasperschnack** [agkozak/zsh-z#84] opened 2023-11-07 20:23 UTC
## Environment
- OS: Mac OS 12.7.1 
- Zsh version: zsh 5.8.1 (x86_64-apple-darwin21.0)

## Description
A delay of 2-3 seconds occurs in the shell prompt after using the `z` command to navigate to a new folder. This behavior suggests that the `_zshz_update_datafile` function is performing an operation that is not completing promptly.

## Expected Behavior
The prompt should return immediately after navigating to a new directory using the `z` command, without any noticeable delay.

## Actual Behavior
After using the `z` command, there is a 2-3 second delay before the prompt reappears.

## Steps to Reproduce
1. Navigate to a new directory using the `z` command.
2. Execute a simple command like `echo "hello"`.
3. Observe the delay before the prompt returns.

## Debug Output Snippet
The debug output indicates that the `_zshz_update_datafile` function is being executed and is likely causing the delay:
+_zshz_update_datafile:56> x=/some/path
+_zshz_update_datafile:57> print -u 14 -- '/some/path|123|timestamp'
... (repeated for multiple directories)
+zshz:592> return

## Possible Causes
- The `_zshz_update_datafile` function might be inefficiently handling the update of the data file after using the `z` command.

## Additional Information
- The delay only occurs after having used the `z` functionality to navigate to a new folder, not on shell startup or when executing other commands.
- Commenting out `zshz` from `.zshrc` seems to improve performance, indicating that the issue is likely within the `zshz` functionality.

## Workaround Attempted
- None yet, aside from avoiding the use of the `z` command, which is not a desirable long-term solution.

## Request
Guidance on how to resolve or mitigate this delay would be greatly appreciated, whether through configuration changes, optimizations, or updates to the `zshz` script.

---

Thank you for your assistance.

**Comment by agkozak** [comment] 2023-11-07 22:12
Sorry to hear you're having this problem. It's one I don't think I've heard reported before. I'm sure we'll get it sorted out, though -- and thanks for reporting it.

I don't suppose you'd be willing to share your `.zshrc`? Sometimes that makes identifying your specific situation much easier.

**Comment by agkozak** [comment] 2023-12-07 00:58
Thanks for providing your `.zshrc`. I don't have a Mac to test it with, but I tried it on the slowest computer I have (an old Raspberry Pi), and I could not reproduce the lag you report.

Can you do an experiment for me? Run

    cd ~/.oh-my-zsh
    git checkout bf7c1b16
    zsh

and see if it makes a difference.

When you're done playing around with that, you can return to your original configuration using

    cd ~/.oh-my-zsh
    git checkout master

Thanks -- let me know how it goes.

**Comment by jsirex** [comment] 2024-05-23 14:45
I noticed that this function runs every time I change directory, and it is complicated and do a lot of things multiple time.

I just did:
``` bash
set -x
cd /
cd /tmp
```

**Comment by agkozak** [comment] 2024-05-23 16:02
@jsirex Every time you press Enter at the prompt, Zsh-z reads your datafile (usually `~/.z`) and updates each line in it and then writes the results back to the file. This work is absolutely necessary for the plugin to work, and the code is highly optimized -- there are minimal forks and no invocations of external utilities.

**Comment by agkozak** [comment] 2024-05-23 16:06
@kasperschnack Did you try my experiment? Have you had any success?

**Comment by kasperschnack** [comment] 2024-06-05 16:24
@agkozak thank you for the mention! I found out that the main cause of the slowness was actually that the git repos I was navigating to was tracking a huge bunch of files. The issues i was seeing disappeared after i made sure to maintain my .gitignore more thoroughly!

**Comment by agkozak** [comment] 2024-06-05 17:11
@kasperschnack I'm glad you sorted it out. I'll close this issue.

**Closed by agkozak** 2024-06-05 17:11 UTC
